# Generated by Django 4.0.5 on 2022-06-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', '男性'), ('Female', '女性'), ('Others', 'その他')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_adviser',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
