# Generated by Django 4.0.5 on 2022-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='hp',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='profile',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='tiktok',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='wear',
            field=models.URLField(null=True),
        ),
    ]
