# Generated by Django 4.0.5 on 2022-07-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0004_adviser_facebook_adviser_height_adviser_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adviser',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
