# Generated by Django 4.0.5 on 2022-07-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0006_alter_adviser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='hp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='wear',
            field=models.URLField(blank=True, null=True),
        ),
    ]
