# Generated by Django 4.0.5 on 2022-07-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
