# Generated by Django 4.0.5 on 2022-07-07 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0010_adviser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adviser', to=settings.AUTH_USER_MODEL),
        ),
    ]
