# Generated by Django 4.0.5 on 2022-07-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0014_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='no-user-image-icon-27.png', null=True, upload_to=''),
        ),
    ]
