# Generated by Django 4.0.5 on 2022-07-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0015_alter_adviser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
