# Generated by Django 4.0.5 on 2022-07-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0017_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='no-user-image-icon-27.jpg', null=True, upload_to=''),
        ),
    ]
