# Generated by Django 4.0.5 on 2022-07-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0020_chatmessage_thread_delete_message_chatmessage_thread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
