# Generated by Django 4.0.5 on 2022-07-15 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0022_alter_chatmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 14, 55, 13, 777745)),
        ),
    ]
