# Generated by Django 4.0.5 on 2022-07-18 04:34

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0025_alter_review_comment_alter_review_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bone',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ストレート', 'ストレート'), ('ウェーブ', 'ウェーブ'), ('ナチュラル', 'ナチュラル')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('スプリング', 'スプリング'), ('サマー', 'サマー'), ('オータム', 'オータム'), ('ウィンター', 'ウィンター')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 13, 34, 45, 719247)),
        ),
    ]
