# Generated by Django 4.0.5 on 2022-07-18 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0027_rename_bone_user_bone_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colortype',
            name='user',
        ),
        migrations.AlterField(
            model_name='thread',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 18, 11, 53, 314714)),
        ),
        migrations.DeleteModel(
            name='BoneType',
        ),
        migrations.DeleteModel(
            name='ColorType',
        ),
    ]
