# Generated by Django 4.0.5 on 2022-07-22 10:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0028_remove_colortype_user_alter_thread_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviser',
            name='height',
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(110), django.core.validators.MaxValueValidator(230)]),
        ),
        migrations.AlterField(
            model_name='thread',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 19, 16, 49, 474279)),
        ),
    ]
