# Generated by Django 4.0.5 on 2022-07-25 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0029_remove_adviser_height_user_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 13, 38, 9, 933657)),
        ),
    ]
