# Generated by Django 3.2.14 on 2022-07-26 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0032_alter_thread_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 20, 24, 54, 548175)),
        ),
    ]
