# Generated by Django 3.2.14 on 2022-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthling', '0033_alter_thread_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
